parameters:
  clickandmortar.import_bundle.reader_dispatcher.class: ClickAndMortar\ImportBundle\Reader\ReaderDispatcher

  # Readers
  clickandmortar.import_bundle.reader.csv_reader.class: ClickAndMortar\ImportBundle\Reader\Readers\CsvReader

services:
  clickandmortar.import_bundle.reader_dispatcher:
    class: %clickandmortar.import_bundle.reader_dispatcher.class%

  # Readers
  clickandmortar.import_bundle.reader.csv_reader:
    class: %clickandmortar.import_bundle.reader.csv_reader.class%
    tags:
      - { name: clickandmortar.import.reader }